let mistakeCounter = 0
let mistakesLog = []
function addFormTracker(){
    let form = document.forms.autogenerated_form

    form.addEventListener("focusin", (event) =>{

    console.log("Filling form started")

    const start = new Date().getTime();
    form.removeEventListener("focusin", timeInForm(form, start), true)
        }, {once: true})


    function timeInForm(form, start){
        form.addEventListener("submit", (event) => {
            event.preventDefault()
            if (!submitForm()) return 0
            const end = new Date().getTime();
            console.log('Time on form: ' + (end - start) + 'ms');
        })
    }
}

function mistakeCount() {
    mistakeCounter++
    console.log("Mistakes - " + mistakeCounter)
}